site_name: Download Service
nav:
  - Home: index.md
  - About: about.md
theme:
  name: material
  logo: assets/logo.png
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode